#if !defined(AFX_LISTVIEW_H__060CA330_BDA1_4DB3_AFDA_C2AD9BC80F0C__INCLUDED_)
#define AFX_LISTVIEW_H__060CA330_BDA1_4DB3_AFDA_C2AD9BC80F0C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CColumnHeaders;
class CListItem;
class CListItems;
class CPicture;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CListView1 wrapper class

class CListView1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CListView1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbdd1f04b, 0x858b, 0x11d1, { 0xb1, 0x6a, 0x0, 0xc0, 0xf0, 0x28, 0x36, 0x28 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetArrange();
	void SetArrange(long nNewValue);
	CColumnHeaders GetColumnHeaders();
	void SetColumnHeaders(LPDISPATCH newValue);
	CListItem GetDropHighlight();
	void SetRefDropHighlight(LPDISPATCH newValue);
	void SetDropHighlight(VARIANT* newValue);
	BOOL GetHideColumnHeaders();
	void SetHideColumnHeaders(BOOL bNewValue);
	BOOL GetHideSelection();
	void SetHideSelection(BOOL bNewValue);
	LPDISPATCH GetIcons();
	void SetRefIcons(LPDISPATCH newValue);
	void SetIcons(LPDISPATCH newValue);
	CListItems GetListItems();
	void SetListItems(LPDISPATCH newValue);
	long GetLabelEdit();
	void SetLabelEdit(long nNewValue);
	BOOL GetLabelWrap();
	void SetLabelWrap(BOOL bNewValue);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	BOOL GetMultiSelect();
	void SetMultiSelect(BOOL bNewValue);
	CListItem GetSelectedItem();
	void SetRefSelectedItem(LPDISPATCH newValue);
	void SetSelectedItem(VARIANT* newValue);
	LPDISPATCH GetSmallIcons();
	void SetRefSmallIcons(LPDISPATCH newValue);
	void SetSmallIcons(LPDISPATCH newValue);
	BOOL GetSorted();
	void SetSorted(BOOL bNewValue);
	short GetSortKey();
	void SetSortKey(short nNewValue);
	long GetSortOrder();
	void SetSortOrder(long nNewValue);
	long GetView();
	void SetView(long nNewValue);
	long GetOLEDragMode();
	void SetOLEDragMode(long nNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	long GetAppearance();
	void SetAppearance(long nNewValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	COleFont GetFont();
	void SetRefFont(LPDISPATCH newValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	long GetHWnd();
	void SetHWnd(long nNewValue);
	CListItem FindItem(LPCTSTR sz, VARIANT* Where, VARIANT* Index, VARIANT* fPartial);
	CListItem GetFirstVisible();
	CListItem HitTest(float x, float y);
	void StartLabelEdit();
	void OLEDrag();
	void Refresh();
	BOOL GetAllowColumnReorder();
	void SetAllowColumnReorder(BOOL bNewValue);
	BOOL GetCheckboxes();
	void SetCheckboxes(BOOL bNewValue);
	BOOL GetFlatScrollBar();
	void SetFlatScrollBar(BOOL bNewValue);
	BOOL GetFullRowSelect();
	void SetFullRowSelect(BOOL bNewValue);
	BOOL GetGridLines();
	void SetGridLines(BOOL bNewValue);
	BOOL GetHotTracking();
	void SetHotTracking(BOOL bNewValue);
	BOOL GetHoverSelection();
	void SetHoverSelection(BOOL bNewValue);
	CPicture GetPicture();
	void SetPicture(LPDISPATCH newValue);
	void SetRefPicture(LPDISPATCH newValue);
	long GetPictureAlignment();
	void SetPictureAlignment(long nNewValue);
	LPDISPATCH GetColumnHeaderIcons();
	void SetRefColumnHeaderIcons(LPDISPATCH newValue);
	void SetColumnHeaderIcons(LPDISPATCH newValue);
	long GetTextBackground();
	void SetTextBackground(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LISTVIEW_H__060CA330_BDA1_4DB3_AFDA_C2AD9BC80F0C__INCLUDED_)
