#if !defined(AFX_LISTITEM_H__E73047A9_D1C4_4E4F_AF26_B9FEA4712AB8__INCLUDED_)
#define AFX_LISTITEM_H__E73047A9_D1C4_4E4F_AF26_B9FEA4712AB8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;
class CListSubItems;

/////////////////////////////////////////////////////////////////////////////
// CListItem wrapper class

class CListItem : public COleDispatchDriver
{
public:
	CListItem() {}		// Calls COleDispatchDriver default constructor
	CListItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CListItem(const CListItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	BOOL GetGhosted();
	void SetGhosted(BOOL bNewValue);
	float GetHeight();
	void SetHeight(float newValue);
	VARIANT GetIcon();
	void SetIcon(const VARIANT& newValue);
	long GetIndex();
	void SetIndex(long nNewValue);
	CString GetKey();
	void SetKey(LPCTSTR lpszNewValue);
	float GetLeft();
	void SetLeft(float newValue);
	BOOL GetSelected();
	void SetSelected(BOOL bNewValue);
	VARIANT GetSmallIcon();
	void SetSmallIcon(const VARIANT& newValue);
	VARIANT GetTag();
	void SetTag(const VARIANT& newValue);
	float GetTop();
	void SetTop(float newValue);
	float GetWidth();
	void SetWidth(float newValue);
	CString GetSubItems(short Index);
	void SetSubItems(short Index, LPCTSTR lpszNewValue);
	CPicture CreateDragImage();
	BOOL EnsureVisible();
	void SetRefTag(const VARIANT& newValue);
	CListSubItems GetListSubItems();
	void SetListSubItems(LPDISPATCH newValue);
	BOOL GetChecked();
	void SetChecked(BOOL bNewValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	CString GetToolTipText();
	void SetToolTipText(LPCTSTR lpszNewValue);
	BOOL GetBold();
	void SetBold(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LISTITEM_H__E73047A9_D1C4_4E4F_AF26_B9FEA4712AB8__INCLUDED_)
