//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Client.rc
//
#define COMPILE_ADMIN_SHOT              0
#define COMPILE_ADMIN                   0
#define IDC_MYICON                      2
#define ID_CREATE_ACCOUNT               3
#define IDC_WEB_PAGE                    3
#define ID_WHERE_ARE_MY_CHIPS           3
#define ID_MISC_CHIP_ACTION_BUTTON      3
#define IDC_RETRIEVE_USERID             3
#define IDC_APPLY                       3
#define IDC_MYICON2                     3
#define IDC_RETRIEVE_PLAYERID           4
#define IDC_RETRIEVE_USERID2            4
#define IDC_NEXT_UNUSED                 5
#define IDC_RETRIEVE_EMAIL              5
#define IDC_PREV_UNUSED                 6
#define IDC_RETRIEVE_NAME               6
#define IDC_DELETE_ACCOUNT              7
#define IDC_RETRIEVE_PASTE              7
#define IDD_CLIENT_DIALOG               102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDM_SHOW_1ON1                   105
#define IDS_HELLO                       106
#define IDI_CLIENT                      107
#define IDI_SMALL                       108
#define IDC_CLIENT                      109
#define IDHOT_EDITACCOUNT               110
#define IDR_MAINFRAME                   128
#define IDD_HOLDEM_LAYOUT               129
#define IDD_CARDROOM                    132
#define IDD_AUTO_UPGRADE_SETTINGS       134
#define IDD_JOIN_WAIT_LIST              136
#define IDD_SEAT_AVAIL                  137
#define IDD_LOGIN                       138
#define IDD_BUY_IN                      139
#define IDD_STUD7_LAYOUT                140
#define IDD_HEADSUP_HOLDEM_LAYOUT       141
#define IDD_CARDROOM2                   142
#define IDD_HOLDEM_LAYOUT_LARGE         142
#define IDD_CARDROOM_LARGE              143
#define IDD_TYPE_CHAT_TEXT              143
#define IDD_DOWNLOAD_STATUS             144
#define IDD_STUD7_LAYOUT_LARGE          145
#define IDD_PROMPT_JOIN_WAIT_LIST       146
#define IDB_SCALED_TABLE                151
#define IDD_LOGGING_IN_STATUS           152
#define IDD_GOING_TO_TABLE              153
#define IDD_CONNECTING                  154
#define IDD_BROADCAST_MESSAGE           155
#define IDB_BITMAP1                     156
#define IDD_REQ_HAND_HISTORY            157
#define IDD_ACCOUNT_EDIT                160
#define IDD_CHANGE_PASSWORD             160
#define IDD_ACCOUNT_CHARGE              161
#define IDD_ACCOUNT_CREATE              163
#define IDD_ACCOUNT_EDIT2               164
#define IDD_CASHIER                     186
#define IDD_ACCOUNT_CREATE2             187
#define IDD_READ_CONTRACT               188
#define IDD_ACCOUNT_CREDIT              189
#define IDD_TRANSFER_MONEY              190
#define IDD_VIEW_TRANSACTIONS           193
#define IDD_ADMIN_CHECK_RUN             194
#define IDD_CHANGE_SHOTCLOCK            195
#define IDD_ADMIN_STATS                 196
#define IDD_CHANGE_EMAIL                197
#define IDD_CHAT_MONITOR                198
#define IDD_EDIT_CREDITABLE             199
#define IDD_GLOBAL_ALLINS               200
#define IDD_BLOCK_COMPUTER              201
#define IDD_SET_ACTIVE_ACCOUNT          202
#define IDD_TABLE_OPTIONS               203
#define IDD_CC_LIMITS                   204
#define IDD_CHECK_TRACKING              205
#define IDD_SNACKMENU                   206
#define IDD_STUD7_LAYOUT_1ON1           207
#define IDB_BITMAP2                     209
#define IDB_BITMAP_VIP                  210
#define IDB_BITMAP_GREEN                211
#define IDB_BITMAP_RED                  212
#define IDD_BUY_IN_TOURN                213
#define IDI_LOCK                        214
#define IDD_TOURN_EMAIL                 215
#define IDB_LOCK                        216
#define IDD_ACCOUNT_EDIT_ADDRESS        217
#define IDD_EMAIL_SEARCH                218
#define IDD_ADMIN_INFO                  219
#define IDD_REQ_PLAYER_INFO             220
#define IDB_PDLG_FIREPAY                221
#define IDB_PDLG_MASTERCARD             222
#define IDB_PDLG_VISA                   223
#define IDD_SUBMIT_PHONE_NUMBER         224
#define IDD_REQ_XFER_EMAIL              225
#define IDD_DISABLE_CASHIER             229
#define IDD_EMAIL_VALIDATION            230
#define IDD_REALMONEY_ACCOUNT_SETUP1    231
#define IDD_Western_Union               232
#define IDD_Bank_Draft                  233
#define IDI_ICON1                       233
#define IDD_PAYPAL                      234
#define IDI_ICON2                       234
#define IDD_TRANSACTION_DECLINE_SMALL   235
#define IDI_ICON3                       235
#define IDD_TRANSACTION_PROCESS         236
#define IDB_VISA_MASTERCARD             236
#define IDD_TRANSACTION_DECLINE_LARGE   237
#define IDD_ACCOUNT_CHARGE1             238
#define IDD_NEWS                        238
#define IDD_TRANSACTION_DECLINE_SMALL1  239
#define IDD_ACCOUNT_CREDIT1             240
#define IDD_TRANSACTION_DECLINE_SMALL2  241
#define IDD_DOWNLOAD_INQUIRY            242
#define IDD_DOWNLOAD_MUST               243
#define IDD_ACCOUNT                     244
#define IDD_NEW_ACCOUNT                 244
#define IDB_DESERT_LOGO                 252
#define IDB_WELCOME                     254
#define IDD_RETRIEVE_PASSW              255
#define IDB_TAB                         261
#define IDD_BACKUP                      269
#define IDB_LOGO                        270
#define IDB_LOGO2                       272
#define IDI_ICON4                       273
#define IDB_TROPICANA                   274
#define IDB_SPLASH                      276
#define IDB_LOGO3                       278
#define IDB_BITMAP3                     284
#define IDB_BITMAP4                     292
#define IDC_SIT_DOWN_1                  1001
#define IDC_SIT_DOWN_2                  1002
#define IDC_SIT_DOWN_3                  1003
#define IDC_SIT_DOWN_4                  1004
#define IDC_SIT_DOWN_5                  1005
#define IDC_SIT_DOWN_6                  1006
#define IDC_SIT_DOWN_7                  1007
#define IDC_SIT_DOWN_8                  1008
#define IDC_SIT_DOWN_9                  1009
#define IDC_SIT_DOWN_10                 1010
#define IDC_FLOP                        1011
#define IDC_DEALER_CHIP_AREA            1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON3                     1014
#define IDC_BUTTON4                     1015
#define IDC_GOTO_GAME                   1016
#define IDC_BUTTON6                     1016
#define IDC_BUTTON_FIREPAY_LOGO         1016
#define IDC_CASHIER                     1017
#define IDC_BUTTON7                     1017
#define IDC_BUTTON_PAYPAL_LOGO          1017
#define IDC_PLAYERPOS_1                 1018
#define IDC_BUTTON8                     1018
#define IDC_BUTTON_MASTERCARD           1018
#define IDC_PLAYERPOS_2                 1019
#define IDC_PLAYERPOS_3                 1020
#define IDC_PLAYERPOS_4                 1021
#define IDC_PLAYERPOS_5                 1022
#define IDC_PLAYERPOS_6                 1023
#define IDC_PLAYERPOS_7                 1024
#define IDC_PLAYERPOS_8                 1025
#define IDC_PLAYERPOS_9                 1026
#define IDC_PLAYERPOS_10                1027
#define IDC_GOTO_CARDROOM               1028
#define IDC_SIT_OUT                     1029
#define IDC_LEAVE_TABLE                 1030
#define IDC_SIT_DOWN_11                 1031
#define IDC_BUTTON5                     1032
#define IDC_BUTTON_DEFAULT              1032
#define IDC_ACTIVATE_CHAT               1032
#define IDC_DEALER_ACTIONS              1032
#define IDC_SNACK_MENU                  1032
#define IDC_CHAT_LIST                   1033
#define IDC_GAME_TYPE_TAB               1034
#define IDC_TABLE_LIST                  1040
#define IDC_LOG_IN                      1043
#define IDC_EXIT                        1044
#define IDC_HIDE_PLAY_MONEY             1045
#define IDC_INFO_HEADER                 1046
#define IDC_TABLE_INFO_HEADER           1046
#define IDC_TABLE_INFO                  1047
#define IDC_ACCOUNT_INFO                1048
#define IDC_JOIN_WAIT_LIST              1049
#define IDC_COMPUTER_PLAY               1050
#define IDC_STAY_ON_WAIT_LIST           1050
#define IDC_NEWS                        1050
#define IDC_FOLD_IN_TURN                1051
#define IDC_ONLINE_HELP                 1051
#define IDC_RADIO1                      1052
#define IDC_POST_IN_TURN                1052
#define IDC_CONTACT_MANAGEMENT          1052
#define IDC_BUY_IN_RADIO_MAX            1052
#define IDC_MALE                        1052
#define IDC_RADIO_REQ_SINGLE_HAND       1052
#define IDC_RADIO_SRC_AVAIL             1052
#define IDC_RADIO_BLOCK                 1052
#define IDC_RADIO_LOWER_LIMITS          1052
#define IDC_RADIO_DHL                   1052
#define IDC_RADIO_BROADCAST_BLAST       1052
#define IDC_RADIO_CHECKRUN_PAGE1        1052
#define IDC_RADIO_EMAIL                 1052
#define IDC_RADIO2                      1053
#define IDC_BUY_IN_RADIO_USR            1053
#define IDC_FEMALE                      1053
#define IDC_RADIO_REQ_MULTIPLE_HANDS    1053
#define IDC_RADIO_SRC_PENDING           1053
#define IDC_RADIO_UNBLOCK               1053
#define IDC_RADIO_HIGHER_LIMITS         1053
#define IDC_RADIO_CERTIFIED             1053
#define IDC_RADIO_BROADCAST_DEALER      1053
#define IDC_RADIO_CHECKRUN_PAGE2        1053
#define IDC_RADIO_NAME                  1053
#define IDC_RADIO_USERID                1053
#define IDC_CHAT_TEXT_BOTH              1054
#define IDC_RADIO3                      1054
#define IDC_CALL_IN_TURN                1054
#define IDC_RADIO_DEST_AVAIL            1054
#define IDC_RADIO_REGISTERED            1054
#define IDC_RADIO_CHECKRUN_PAGE3        1054
#define IDC_RADIO_NAME2                 1054
#define IDC_RADIO_FIREPAY1              1054
#define IDC_RADIO_FIREPAY               1054
#define IDC_RADIO4                      1055
#define IDC_RAISE_IN_TURN               1055
#define IDC_RADIO_MASTERCARD            1055
#define IDC_RADIO_DEST_PENDING          1055
#define IDC_RADIO_EXPRESS               1055
#define IDC_RADIO_CHECKRUN_PAGE4        1055
#define IDC_RADIO5                      1056
#define IDC_CAP_IT                      1056
#define IDC_RADIO_AMEX                  1056
#define IDC_FOLD_IN_TURN2               1056
#define IDC_RADIO_DEST_PENDING_CHECK    1056
#define IDC_RADIO_UPS                   1056
#define IDC_RADIO_TRANS_EXPRESS         1056
#define IDC_BUTTON_FIREPAY_SETUP        1056
#define IDC_RADIO_PAYPAL                1056
#define IDC_RADIO6                      1057
#define IDC_CALL_IN_TURN2               1057
#define IDC_RADIO_SRC_PENDING_CHECK     1057
#define IDC_RADIO_FEDEX                 1057
#define IDC_RADIO_VISA1                 1057
#define IDC_RADIO_VISA                  1057
#define IDC_SPIN1                       1058
#define IDC_RADIO7                      1058
#define IDC_SPIN_HAND_REQ               1058
#define IDC_COMPUTER_PLAY_SECS_SPIN     1058
#define IDC_PLAYERID_SPIN               1058
#define IDC_ALLINS_ALLOWED_SPINNER      1058
#define IDC_SET_MAX_ALLOWABLE_SPINNER   1058
#define IDC_RADIO_PRIORITY              1058
#define IDC_XFER_NONE                   1058
#define IDC_REQINFO_SPIN                1058
#define IDC_MIN_PLAYERS_SPINNER2        1059
#define IDC_MIN_PLAYERS_SPINNER         1059
#define IDC_RADIO8                      1059
#define IDC_LOW_PLAYERS_COUNT_SPIN      1059
#define IDC_SPIN2                       1059
#define IDC_HANDCOUNT_SPIN              1059
#define IDC_MAX_GOOD_ALLINS_ALLOWED_SPINNER 1059
#define IDC_RADIO_NONE                  1059
#define IDC_XFER_DEFAULT                1059
#define IDC_SPIN_EMAILSEARCH            1059
#define IDC_PLAYERINFO_1                1060
#define IDC_RADIO9                      1060
#define IDC_XFER_TOANDFROM              1060
#define IDC_SPIN_USERID                 1060
#define IDC_PLAYERINFO_2                1061
#define IDC_MIN_PLAYERS_VALUE           1061
#define IDC_XFER_TREATASPURCHASE        1061
#define IDC_PLAYERINFO_3                1062
#define IDC_WAIT_SINGLE_TABLE           1062
#define IDC_XFER_CUSTOM                 1062
#define IDC_PLAYERINFO_4                1063
#define IDC_WAIT_ANY_TABLE              1063
#define IDC_PLAYERINFO_5                1064
#define IDC_WAIT_SINGLE_TABLE_TEXT      1064
#define IDC_PLAYERINFO_6                1065
#define IDC_CURRENT_OPTIONS_TEXT        1065
#define IDC_PLAYERINFO_7                1066
#define IDC_PLAYERINFO_8                1067
#define IDC_PLAYERINFO_9                1068
#define IDC_PLAYERINFO_10               1069
#define IDC_WAIT_LIST_STATUS            1070
#define IDC_SEAT_AVAIL_TEXT             1071
#define IDC_RAISE_IN_TURN2              1071
#define IDC_EDIT_PASSWORD               1072
#define IDC_EDIT_LOGIN_PASSWORD         1072
#define IDC_EDIT_LOGIN                  1073
#define IDC_EDIT_LOGIN_NAME             1073
#define IDC_CHECK1                      1074
#define IDC_CHECK_REMEMBER_SETTINGS     1074
#define IDC_CHECK_REMEMBER_CC_INFO      1074
#define IDC_ADMIN_FLAG                  1074
#define IDC_ANNOUNCE_AT_TABLES          1074
#define IDC_ISSUE_CHECK1                1074
#define IDC_HH_ADMIN_CHECK              1074
#define IDC_CHECK_MONITOR_PLAY          1074
#define IDC_CHECK_LIMIT1                1074
#define IDC_CHKBOX_TREAT_AS_CC          1074
#define IDC_CHKBOX_NO_SMOKING           1074
#define IDC_SEND_TO_REAL_MONEY          1074
#define IDC_CHECK_DISABLE               1074
#define IDC_CHECK_EMAIL_ADMIN           1074
#define IDC_CHKBOX_SAVE_CARD_INFO       1074
#define IDC_CHAT_TEXT_DEALER            1075
#define IDC_SHUTDOWN_WHEN_DONE          1075
#define IDC_ISSUE_CHECK2                1075
#define IDC_CHECK_MONITOR_REAL          1075
#define IDC_CHECK_LIMIT2                1075
#define IDC_SEND_TO_PLAY_MONEY          1075
#define IDC_CHKBOX_NO_HISTORY_ENTRY     1075
#define IDC_CHECK_EMAIL_SUPPORT         1075
#define IDC_CHECK10                     1075
#define IDC_CHAT_TEXT_PLAYERS           1076
#define IDC_ISSUE_CHECK3                1076
#define IDC_SHUTDOWN_IS_BRIEF           1076
#define IDC_CHECK_LIMIT3                1076
#define IDC_SEND_TO_TOURNAMENT          1076
#define IDC_CHECK_MONITOR_TOURN         1076
#define IDC_EDIT_CHIPS                  1077
#define IDC_ISSUE_CHECK4                1077
#define IDC_RESTART_NEW_SERVER          1077
#define IDC_TABLE_GAME_SERIAL_NUM       1078
#define IDC_ISSUE_CHECK5                1078
#define IDC_CHKBOX_CLOSE_CASHIER        1078
#define IDC_BUY_IN_LIMITS               1079
#define IDC_WATCHING_COUNT              1079
#define IDC_ISSUE_CHECK6                1079
#define IDC_CHKBOX_CASHIER_AUTO_UP_DOWN 1079
#define IDC_POTS                        1079
#define IDC_BUY_IN_TABLE                1080
#define IDC_RECONNECT                   1080
#define IDC_TOTAL_CONNECTIONS           1080
#define IDC_ISSUE_CHECK7                1080
#define IDC_CHKBOX_TOURNAMENT_STARTING_ALLOWED 1080
#define IDC_BUY_IN_MINIMUM              1081
#define IDC_ISSUE_CHECK8                1081
#define IDC_I_USE_AOL                   1081
#define IDC_CHKBOX_TOURNAMENT_SITDOWN_ALLOWED 1081
#define IDC_CHAT_BOX                    1082
#define IDC_ISSUE_CHECK9                1082
#define IDC_CHKBOX_TOURNAMENT_EMERGENCY_SHUTDOWN 1082
#define IDC_EDIT_CHAT_TEXT              1083
#define IDC_TYPE_CHAT                   1083
#define IDC_ISSUE_CHECK10               1083
#define IDC_ISSUE_CHECK11               1084
#define IDC_TABLE_ID                    1085
#define IDC_ISSUE_CHECK12               1085
#define IDC_PROGRESS                    1086
#define IDC_ISSUE_CHECK13               1086
#define IDC_CURRENT_FILE                1087
#define IDC_ISSUE_CHECK14               1087
#define IDC_BYTES_TO_GO                 1088
#define IDC_ISSUE_CHECK15               1088
#define IDC_STATUS                      1089
#define IDC_ISSUE_CHECK16               1089
#define IDC_STATIC_ABOUT1               1090
#define IDC_ISSUE_CHECK17               1090
#define IDC_STATIC_ABOUT2               1091
#define IDC_ISSUE_CHECK18               1091
#define IDC_TASKS                       1091
#define IDC_STATIC_DATETIME             1092
#define IDC_ISSUE_CHECK19               1092
#define IDC_OUR_PICTURE                 1093
#define IDC_STATIC_ABOUT3               1093
#define IDC_ISSUE_CHECK20               1093
#define IDC_POT1                        1094
#define IDC_ISSUE_CHECK21               1094
#define IDC_POT2                        1095
#define IDC_ISSUE_CHECK22               1095
#define IDC_CHIPS_PLR1                  1096
#define IDC_ISSUE_CHECK23               1096
#define IDC_CHIPS_RAKE                  1097
#define IDC_ISSUE_CHECK24               1097
#define IDC_CHIPS_PLR2                  1098
#define IDC_ISSUE_CHECK25               1098
#define IDC_CHIPS_PLR3                  1099
#define IDC_ISSUE_CHECK26               1099
#define IDC_CHIPS_PLR4                  1100
#define IDC_ISSUE_CHECK27               1100
#define IDC_CHIPS_PLR5                  1101
#define IDC_ISSUE_CHECK28               1101
#define IDC_CHIPS_PLR6                  1102
#define IDC_ISSUE_CHECK29               1102
#define IDC_CHIPS_PLR7                  1103
#define IDC_ISSUE_CHECK30               1103
#define IDC_CHIPS_PLR8                  1104
#define IDC_ISSUE_CHECK31               1104
#define IDC_CHIPS_PLR9                  1105
#define IDC_ISSUE_CHECK32               1105
#define IDC_CHIPS_PLR10                 1106
#define IDC_ISSUE_CHECK33               1106
#define IDC_CARDS_PLR1                  1107
#define IDC_ISSUE_CHECK34               1107
#define IDC_CARDS_PLR2                  1108
#define IDC_ISSUE_CHECK35               1108
#define IDC_CARDS_PLR3                  1109
#define IDC_ISSUE_CHECK36               1109
#define IDC_CARDS_PLR4                  1110
#define IDC_ISSUE_CHECK37               1110
#define IDC_CARDS_PLR5                  1111
#define IDC_ISSUE_CHECK38               1111
#define IDC_CARDS_PLR6                  1112
#define IDC_ISSUE_CHECK39               1112
#define IDC_CARDS_PLR7                  1113
#define IDC_ISSUE_CHECK40               1113
#define IDC_CARDS_PLR8                  1114
#define IDC_ISSUE_CHECK41               1114
#define IDC_CARDS_PLR9                  1115
#define IDC_ISSUE_CHECK42               1115
#define IDC_CARDS_PLR10                 1116
#define IDC_ISSUE_CHECK43               1116
#define IDC_CARDS_FLOP                  1117
#define IDC_ISSUE_CHECK44               1117
#define IDC_SMALL_CARD_PLR1             1118
#define IDC_ISSUE_CHECK45               1118
#define IDC_SMALL_CARD_PLR2             1119
#define IDC_ISSUE_CHECK46               1119
#define IDC_SMALL_CARD_PLR3             1120
#define IDC_ISSUE_CHECK47               1120
#define IDC_SMALL_CARD_PLR4             1121
#define IDC_ISSUE_CHECK48               1121
#define IDC_SMALL_CARD_PLR5             1122
#define IDC_SMALL_CARD_PLR6             1123
#define IDC_SMALL_CARD_PLR7             1124
#define IDC_SMALL_CARD_PLR8             1125
#define IDC_SMALL_CARD_PLR9             1126
#define IDC_SMALL_CARD_PLR10            1127
#define IDC_TEXT_POT1                   1128
#define IDC_SNACK_PLR1                  1128
#define IDC_POT3                        1129
#define IDC_STATIC_BIG_BLIND            1129
#define IDC_STATIC_TABLE_INFO           1129
#define IDC_TEXT_POT2                   1130
#define IDC_TEXT1                       1130
#define IDC_STATIC_CHIPS                1130
#define IDC_SNACK_PLR2                  1130
#define IDC_TEXT_POT3                   1131
#define IDC_TEXT2                       1131
#define IDC_STATIC_MINIMUM              1131
#define IDC_SNACK_PLR3                  1131
#define IDC_DECK_LOCATION               1132
#define IDC_TEXT3                       1132
#define IDC_STATIC_LOW_PLAY_CHIPS       1132
#define IDC_ISSUE_CHECK49               1132
#define IDC_LOGIN_DETAIL_MSG            1133
#define IDC_ISSUE_CHECK50               1133
#define IDC_SNACK_PLR4                  1133
#define IDC_STATIC_LOGO                 1134
#define IDC_ISSUE_CHECK51               1134
#define IDC_SNACK_PLR5                  1134
#define IDC_USER_COUNT                  1135
#define IDC_ISSUE_CHECK52               1135
#define IDC_SNACK_PLR6                  1135
#define IDC_BEST_HAND                   1136
#define IDC_ISSUE_CHECK53               1136
#define IDC_MAIN_POT_HOVER              1137
#define IDC_ISSUE_CHECK54               1137
#define IDC_SIDE_POT1_HOVER             1138
#define IDC_CONNECTION_PROGRESS         1138
#define IDC_ISSUE_CHECK55               1138
#define IDC_SIDE_POT2_HOVER             1139
#define IDC_CONNECTION_STATUS           1139
#define IDC_ISSUE_CHECK56               1139
#define IDC_HOVER_PLAYER1               1140
#define IDC_MESSAGE_TEXT                1140
#define IDC_ISSUE_CHECK57               1140
#define IDC_HOVER_PLAYER2               1141
#define IDC_ISSUE_CHECK58               1141
#define IDC_MESSAGE_TEXT2               1141
#define IDC_HOVER_PLAYER3               1142
#define IDC_ISSUE_CHECK59               1142
#define IDC_MESSAGE_TEXT1_EXPIRED       1142
#define IDC_HOVER_PLAYER4               1143
#define IDC_ISSUE_CHECK60               1143
#define IDC_MESSAGE_TEXT2_EXPIRED       1143
#define IDC_HOVER_PLAYER5               1144
#define IDC_HOVER_PLAYER6               1145
#define IDC_HOVER_PLAYER7               1146
#define IDC_HOVER_PLAYER8               1147
#define IDC_HOVER_PLAYER9               1148
#define IDC_ISSUE_CHECK61               1148
#define IDC_SNACK_PLR11                 1148
#define IDC_HOVER_PLAYER10              1149
#define IDC_ISSUE_CHECK62               1149
#define IDC_SNACK_PLR12                 1149
#define IDC_BROADCAST_MESSAGE           1150
#define IDC_PLAYERINFO_1_OLD            1150
#define IDC_ISSUE_CHECK63               1150
#define IDC_LOWEST_HAND                 1150
#define IDC_REQUEST_HAND_HISTORY        1151
#define IDC_EDIT_GAME_NUM               1151
#define IDC_EDIT_REQ_HAND_NUM           1151
#define IDC_ISSUE_CHECK64               1151
#define IDC_SNACK_PLR7                  1151
#define IDC_SNACK_PLR13                 1151
#define IDC_MY_MONEY                    1151
#define IDC_EDIT1                       1152
#define IDC_AMOUNT                      1152
#define IDC_KICK_OFF                    1152
#define IDC_LOGIN_SOURCE                1152
#define IDC_GRAND_TOTAL                 1152
#define IDC_CHAT_MONITOR_VIEW           1152
#define IDC_CREDITABLE_EDIT             1152
#define IDC_ALLINS_ALLOWED              1152
#define IDC_SNACK_PLR8                  1152
#define IDC_SNACK_PLR14                 1152
#define IDC_CHECK2                      1153
#define IDC_DONOTSEND1                  1153
#define IDC_CHKBOX_NOJUNKMAIL           1153
#define IDC_ISSUE_CHECK65               1153
#define IDC_MAX_GOOD_ALLINS_ALLOWED     1153
#define IDC_SNACK_PLR9                  1153
#define IDC_SNACK_PLR15                 1153
#define IDC_REQINFO_PLAYERINFO          1153
#define IDC_DAY                         1153
#define IDC_CHECK3                      1154
#define IDC_DONOTSEND2                  1154
#define IDC_CHKBOX_EMAIL_WHEN_REAL      1154
#define IDC_ISSUE_CHECK66               1154
#define IDC_CHECK_MONITOR_SOUND         1154
#define IDC_SNACK_PLR10                 1154
#define IDC_SNACK_PLR16                 1154
#define IDC_CHKBOX_TOURNAMENTS_OPEN     1154
#define IDC_YEAR                        1154
#define IDC_EDIT2                       1155
#define IDC_CITY                        1155
#define IDC_EDIT_CREDITADMIN            1155
#define IDC_ISSUE_CHECK67               1155
#define IDC_CHATMON_EDIT                1155
#define IDC_SNACK_PLR17                 1155
#define IDC_TRANSACTION_NUMBER          1155
#define IDC_EDIT_DELIVERY_AMOUNT        1155
#define IDC_SMALL_CARD_PLR11            1155
#define IDC_EDIT3                       1156
#define IDC_CHKBOX_LOCKEDOUT            1156
#define IDC_STATE                       1156
#define IDC_ISSUE_CHECK68               1156
#define IDC_XFER_CUSTOM_MESSAGE         1156
#define IDC_EDIT4                       1157
#define IDC_USERID                      1157
#define IDC_ISSUE_CHECK69               1157
#define IDC_EDIT5                       1158
#define IDC_PASSWORD                    1158
#define IDC_TRANSFER_REASON             1158
#define IDC_ISSUE_CHECK70               1158
#define IDC_SECRET_ANSWER               1158
#define IDC_CHECK11                     1158
#define IDC_EDIT6                       1159
#define IDC_EMAIL                       1159
#define IDC_ISSUE_CHECK71               1159
#define IDC_EDIT7                       1160
#define IDC_PASSWORD2                   1160
#define IDC_USERID2                     1160
#define IDC_USERID1                     1160
#define IDC_ISSUE_CHECK72               1160
#define IDC_VALIDATION_CODE             1160
#define IDC_EMAIL3                      1160
#define IDC_EDIT8                       1161
#define IDC_USERID3                     1161
#define IDC_PLAYERID                    1161
#define IDC_CARD_ADDRESS1               1161
#define IDC_COUNTRY                     1161
#define IDC_ISSUE_CHECK73               1161
#define IDC_USERID_2                    1161
#define IDC_EMAIL2                      1161
#define IDC_EDIT9                       1162
#define IDC_USERID4                     1162
#define IDC_HANDCOUNT                   1162
#define IDC_CARD_CITY                   1162
#define IDC_POSTAL_CODE                 1162
#define IDC_ISSUE_CHECK74               1162
#define IDC_EDIT10                      1163
#define IDC_USERID5                     1163
#define IDC_REALMONEY                   1163
#define IDC_CARD_ADDRESS2               1163
#define IDC_ISSUE_CHECK75               1163
#define IDC_USER_MI                     1163
#define IDC_EDIT11                      1164
#define IDC_USERID6                     1164
#define IDC_REALMONEY_INPLAY            1164
#define IDC_CARD_ZIP                    1164
#define IDC_ISSUE_CHECK76               1164
#define IDC_EDIT12                      1165
#define IDC_USERID7                     1165
#define IDC_PLAYMONEY                   1165
#define IDC_CARD_NAME                   1165
#define IDC_REALMONEY2                  1165
#define IDC_ISSUE_CHECK77               1165
#define IDC_EDIT13                      1166
#define IDC_USERID8                     1166
#define IDC_PLAYMONEY_INPLAY            1166
#define IDC_CARD_EXP_MONTH              1166
#define IDC_REALMONEY_INPLAY4           1166
#define IDC_ISSUE_CHECK78               1166
#define IDC_EDIT14                      1167
#define IDC_USERID9                     1167
#define IDC_CARD_NUMBER                 1167
#define IDC_CHKBOX_EMAIL_INVALID        1167
#define IDC_ISSUE_CHECK79               1167
#define IDC_CHECK4                      1168
#define IDC_MAGAZINE                    1168
#define IDC_CARD_EXP_YEAR               1168
#define IDC_CHKBOX_NO_NEWS              1168
#define IDC_ISSUE_CHECK80               1168
#define IDC_CHECK5                      1169
#define IDC_BANNER                      1169
#define IDC_PASSWORD3                   1169
#define IDC_RM_PASSWORD                 1169
#define IDC_REQUEST_HAND_HISTORY2       1169
#define IDC_ISSUE_CHECK81               1169
#define IDC_CHECK6                      1170
#define IDC_NEWSGROUP                   1170
#define IDC_ISSUE_CHECK82               1170
#define IDC_ADMIN_NOTES                 1170
#define IDC_CHECK7                      1171
#define IDC_WEBSITE                     1171
#define IDC_CITY3                       1171
#define IDC_ISSUE_CHECK83               1171
#define IDC_BLOCK_COMPUTER              1171
#define IDC_CHECK8                      1172
#define IDC_WORDOFMOUTH                 1172
#define IDC_CITY2                       1172
#define IDC_EDIT_STATE                  1172
#define IDC_ISSUE_CHECK84               1172
#define IDC_CHECK9                      1173
#define IDC_OTHER                       1173
#define IDC_CITY4                       1173
#define IDC_EDIT_COUNTRY                1173
#define IDC_ISSUE_CHECK85               1173
#define IDC_EDIT15                      1174
#define IDC_BANNER_STR                  1174
#define IDC_REALMONEY_INPLAY2           1174
#define IDC_REALMONEY_PENDING_CREDIT    1174
#define IDC_ISSUE_CHECK86               1174
#define IDC_EDIT16                      1175
#define IDC_MAGAZINE_STR                1175
#define IDC_REALMONEY_INPLAY3           1175
#define IDC_REALMONEY_TOTAL             1175
#define IDC_ISSUE_CHECK87               1175
#define IDC_EDIT17                      1176
#define IDC_NEWSGROUP_STR               1176
#define IDC_POSTAL                      1176
#define IDC_EDIT_POSTAL_CODE            1176
#define IDC_REALMONEY_PENDING_CREDIT2   1176
#define IDC_ISSUE_CHECK88               1176
#define IDC_EDIT18                      1177
#define IDC_WEBSITE_STR                 1177
#define IDC_REALMONEY_TOTAL2            1177
#define IDC_LOGGED_IN_STATUS            1177
#define IDC_ISSUE_CHECK89               1177
#define IDC_EDIT19                      1178
#define IDC_OTHER_STR                   1178
#define IDC_REALMONEY_PENDING_CHECK     1178
#define IDC_REALMONEY_PENDING_CHECK2    1178
#define IDC_ISSUE_CHECK90               1178
#define IDC_PLAYMONEY3                  1178
#define IDC_FULLNAME                    1179
#define IDC_REALMONEY_PENDING_CHECK1    1179
#define IDC_ATLEAST21                   1180
#define IDC_REALMONEY_CCFEE             1180
#define IDC_REALMONEY_CCFEE1            1180
#define IDC_PLAYMONEY_INPLAY3           1180
#define IDC_ADDRESS_LINE1               1181
#define IDC_REALMONEY_CCFEE2            1181
#define IDC_STATIC_REQ_HANDS            1182
#define IDC_ADDRESS_LINE2               1182
#define IDC_EDIT_HAND_REQ_SPIN          1183
#define IDC_CHKBOX_AUTOBLOCK            1183
#define IDC_STATIC_REQ_SIZE             1184
#define IDC_CHKBOX_LOGIN_ALERT          1184
#define IDC_QUIET_DEALER_TEXT           1185
#define IDC_CHKBOX_SQUELCH_CHAT         1185
#define IDC_COMPUTER_PLAY_SECS          1186
#define IDC_CHKBOX_GOOD_ALLIN_ALERT     1186
#define IDC_WATCHING_ACTIVATE           1187
#define IDC_CHKBOX_DUPES_OK             1187
#define IDC_LOW_PLAYERS_ACTIVATE        1188
#define IDC_SHOT_CLOCK_MESSAGE          1188
#define IDC_CHKBOX_EMAIL_BOUNCES        1188
#define IDC_LOW_PLAYERS_COUNT           1189
#define IDC_SHOT_CLOCK_ETA              1189
#define IDC_SAVE                        1189
#define IDC_CHAT_POPUP                  1190
#define IDC_SAVE2                       1190
#define IDC_CHKBOX_NO_ALLIN_RESET       1190
#define IDC_LOGINS                      1191
#define IDC_ALLINS                      1192
#define IDC_HANDS_SEEN                  1193
#define IDC_MUCK_LOSING_HANDS           1193
#define IDC_COMPUTER                    1194
#define IDC_REAL_BANK                   1194
#define IDC_CHKBOX_REAL_PLAYER          1194
#define IDC_REAL_TABLE                  1195
#define IDC_CREDIT_GUESS                1195
#define IDC_DUPE1                       1195
#define IDC_REAL_TOTAL                  1196
#define IDC_DUPE2                       1196
#define IDC_EPTS2                       1196
#define IDC_PLAY_BANK                   1197
#define IDC_REAL_PENDING                1197
#define IDC_DUPE3                       1197
#define IDC_PLAY_TABLE                  1198
#define IDC_DUPE4                       1198
#define IDC_STAR                        1198
#define IDC_PLAY_TOTAL                  1199
#define IDC_DUPE5                       1199
#define IDC_REALMONEY4                  1199
#define IDC_PURCHASE_CHIPS              1200
#define IDC_DUPE6                       1200
#define IDC_REALMONEY_INPLAY6           1200
#define IDC_PAUSE_SENDING               1201
#define IDC_CASH_CHIPS                  1201
#define IDC_DUPE7                       1201
#define IDC_REALMONEY_PENDING_CREDIT5   1201
#define IDC_DUPE8                       1202
#define IDC_TRANSACTION_HISTORY         1202
#define IDC_REALMONEY5                  1202
#define IDC_SETUP_ACCOUNT               1203
#define IDC_CHKBOX_NO_CASHIER           1203
#define IDC_REALMONEY_INPLAY7           1203
#define IDC_CARD_TEST1                  1204
#define IDC_REQ_INFO1                   1204
#define IDC_REQINFO_ALLIN               1204
#define IDC_CARD_TEST2                  1205
#define IDC_CASHIER_USERID              1205
#define IDC_CASHIER_PLAYERINFO          1205
#define IDC_REQ_INFO2                   1205
#define IDC_REQINFO_CHARGEBACK          1205
#define IDC_CASHIER_FULLNAME            1206
#define IDC_READ_DISCLOSURE             1206
#define IDC_REQ_INFO3                   1206
#define IDC_CARD_TEST3                  1206
#define IDC_CHKBOX_USED_FIREPAY         1206
#define IDC_REALMONEY_PENDING_CREDIT6   1206
#define IDC_CASHIER_EMAIL               1207
#define IDC_COMBO_COUNTRY               1207
#define IDC_CHKBOX_SQUELCH_RB_CHAT      1207
#define IDC_CASHIER_ADDRESS1            1208
#define IDC_RETRIEVE_ECASH              1208
#define IDC_CASHIER_ADDRESS2            1209
#define IDC_RETRIEVE_RAKE               1209
#define IDC_RETRIEVE_ECASH2             1209
#define IDC_CASHIER_CITY                1210
#define IDC_RETRIEVE_MARKETING          1210
#define IDC_CASHIER_COUNTRY             1211
#define IDC_RETRIEVE_MISC               1211
#define IDC_CASHIER_ZIP                 1212
#define IDC_TRANSFER_MONEY              1212
#define IDC_RETRIEVE_MARKETING2         1212
#define IDC_RETRIEVE_MISC2              1213
#define IDC_TRANSFER_MONEY2             1213
#define IDC_CCFEE_CREDIT_TEXT           1214
#define IDC_RETRIEVE_PENDING            1214
#define IDC_COMBO_ACCOUNT_PRIV          1214
#define IDC_RETRIEVE_ECASH_FEE          1215
#define IDC_RETRIEVE_PENDING2           1215
#define IDC_TEXT                        1216
#define IDC_RETRIEVE_CHECKS             1216
#define IDC_RETRIEVE_PENDING3           1216
#define IDC_RETRIEVE_CHARGEBACK         1216
#define IDC_DATE_OPENED                 1217
#define IDC_RETRIEVE_CHECKS2            1217
#define IDC_REQUEST_SUMMARY_QUESTION    1217
#define IDC_PLAYER_ADDRESS              1218
#define IDC_RETRIEVE_DRAFTS             1218
#define IDC_CASHOUT_PLAYER              1218
#define IDC_CASHOUT_PLAYER_SPECIFIED    1218
#define IDC_SRC_ACCOUNT_NAME            1219
#define IDC_CASHOUT_PLAYER_ENTIRE       1219
#define IDC_DEST_ACCOUNT_NAME           1220
#define IDC_INITIATE_TRANSFER1          1221
#define IDC_INITIATE_TRANSFER2          1222
#define IDC_CASHOUT_PLAYER_ENTIRE3      1222
#define IDC_BUYIN_LIMITS                1223
#define IDC_RETRIEVE_DRAFTS2            1223
#define IDC_CASHOUT_PLAYER_SPECIFIED3   1223
#define IDC_DATEPICKER                  1224
#define IDC_RETRIEVE_WIRES              1224
#define IDC_TIMEPICKER                  1225
#define IDC_RETRIEVE_WIRES2             1225
#define IDC_DATE_5MIN                   1226
#define IDC_RETRIEVE_CHARGEBACKS        1226
#define IDC_COMBO_CHAT_MODE             1227
#define IDC_DATE_NOW                    1227
#define IDC_RETRIEVE_CHARGEBACKS2       1227
#define IDC_BROADCAST_DEST              1228
#define IDC_RETRIEVE_PRIZES             1228
#define IDC_RETRIEVE_ECASH4             1228
#define IDC_RETRIEVE_MISC3              1229
#define IDC_RETRIEVE_PRIZES2            1229
#define IDC_RETRIEVE_ECASH_FEE3         1229
#define IDC_RESET_ALLINS                1230
#define IDC_STATIC_ADMIN                1231
#define IDC_SET_CCLIMITS                1231
#define IDC_RETRIEVE_MARKETING4         1231
#define IDC_DATE_10MIN                  1232
#define IDC_TRANSACT_HISTORY            1232
#define IDC_RETRIEVE_CHARGEBACK3        1232
#define IDC_DATE_15MIN                  1233
#define IDC_SEND_PASSWORD               1233
#define IDC_DATE_20MIN                  1234
#define IDC_GAIR_LETTER                 1234
#define IDC_DATE_30MIN                  1235
#define IDC_RETRIEVE_MISC5              1235
#define IDC_MSG_SHUTDOWN                1236
#define IDC_RETRIEVE_RAKE3              1236
#define IDC_MSG_CONNECTION_PROBS        1237
#define IDC_UNSELECT_ALL                1237
#define IDC_MSG_WELCOME                 1238
#define IDC_SELECT_ALL                  1238
#define IDC_INVERT_ALL                  1239
#define IDC_SUBMIT                      1239
#define IDC_MSG_SHUTDOWN2               1239
#define IDC_TRANSFER_MONEY5             1239
#define IDC_VALIDATE                    1240
#define IDC_CHATMON_RESET               1240
#define IDC_MSG_SERVER_BACK_UP          1240
#define IDC_REQ_LABELS                  1240
#define IDC_CHATMON_SHOW                1241
#define IDC_CHATMON_APPLY               1241
#define IDC_EDIT_CREDITABLE             1241
#define IDC_MSG_CLOSE_CASHIER           1241
#define IDC_CHATMON_HIDE                1242
#define IDC_SET_ACTIVE_ACCOUNT          1242
#define IDC_DATE_TOP_OF_HOUR            1242
#define IDC_REALMONEY_PENDING_CHECK4    1242
#define IDC_COMBO_TRANSACTIONS          1243
#define IDC_REQ_STATEMENT               1243
#define IDC_MSG_TOURN_OPEN1             1243
#define IDC_REALMONEY_CCFEE4            1243
#define IDC_CHAT_MONITOR_FREEZE         1244
#define IDC_MSG_TOURN_CLOSE1            1244
#define IDC_MSG_TOURN_OPEN2             1245
#define IDC_REALMONEY_TOTAL3            1245
#define IDC_SETTIME_NOW                 1246
#define IDC_MSG_TOURN_CLOSE2            1246
#define IDC_TRANSFER_MONEY7             1246
#define IDC_SERIAL_NUM                  1247
#define IDC_REALMONEY_TOTAL4            1247
#define IDC_MONITOR_SLIDER              1248
#define IDC_STATIC_ALERT_LEVEL          1249
#define IDC_SEATED_AT_1                 1251
#define IDC_SEATED_AT_2                 1252
#define IDC_SERIAL_NUM_S1               1253
#define IDC_SERIAL_NUM_S2               1254
#define IDC_NET_EXPOSURE                1255
#define IDC_SET_MAX_ALLOWABLE_APPLY     1258
#define IDC_SET_MAX_ALLOWABLE_DEFAULT   1259
#define IDC_SET_MAX_ALLOWABLE_BLOCK     1260
#define IDC_SET_MAX_ALLOWABLE_STATIC    1261
#define IDC_SET_MAX_ALLOWABLE_NUMBER    1262
#define IDC_VIEW_ACCOUNTS_PLAYERID      1263
#define IDC_CHAT_MONITOR_CLEAR_ALERTS   1265
#define IDC_CHECK_MONITOR_POPUP         1266
#define IDC_STATIC_TRANSACTION_ORDER    1267
#define IDC_COMBO_CARDNUMBERS           1268
#define IDC_ALL_INS_REMAINING           1269
#define IDC_COMBO_BAR_SNACK             1270
#define IDC_REQUEST_MORE_CHIPS          1271
#define IDC_EDIT_LIMIT1                 1272
#define IDC_SNACKMENU                   1272
#define IDC_EDIT_LIMIT2                 1273
#define IDC_ADMIN_NOTES_LEN             1273
#define IDC_EDIT_LIMIT3                 1274
#define IDC_USERID_1                    1274
#define IDC_RETRIEVE_USERID1            1275
#define IDC_EDIT_TRACKING_NUMBER        1276
#define IDC_DELIVERY_DETAILS            1277
#define IDC_CHECK_TRACKING              1278
#define IDC_COMBO_CHECKNUM              1279
#define IDAPPLY_EMAIL                   1280
#define IDAPPLY_NOEMAIL                 1281
#define IDC_NO_SMOKING                  1281
#define IDNOAPPLY_EMAIL                 1282
#define IDC_NOTHING                     1282
#define IDC_MENU_ITEM1                  1283
#define IDC_MENU_ITEM2                  1285
#define IDC_PURCHASE_FEE                1285
#define IDC_MENU_ITEM3                  1286
#define IDC_CHKBOX_VIP                  1286
#define IDC_MENU_ITEM4                  1287
#define IDC_PICTURE_VIP                 1287
#define IDC_MENU_ITEM5                  1288
#define IDC_PENDING_CC_REFUND           1288
#define IDC_PURCH_1                     1289
#define IDC_MENU_ITEM6                  1290
#define IDC_PURCH_2                     1290
#define IDC_STATIC_GROUP_ID1            1290
#define IDC_MENU_ITEM7                  1291
#define IDC_PURCH_3                     1291
#define IDC_STATIC_GROUP_ID2            1291
#define IDC_MENU_ITEM8                  1292
#define IDC_AVAIL_1                     1292
#define IDC_EXPOSURE_GREEN              1292
#define IDC_MENU_ITEM9                  1293
#define IDC_AVAIL_2                     1293
#define IDC_EXPOSURE_RED                1293
#define IDC_BUY_IN_BUTTON_USR           1293
#define IDC_MENU_ITEM10                 1294
#define IDC_AVAIL_3                     1294
#define IDC_BUY_IN_BUTTON_MAX           1294
#define IDC_MENU_ITEM11                 1295
#define IDC_STATIC_PRIZE_DESCRIPTION    1295
#define IDC_MENU_ITEM12                 1296
#define IDC_GROUP_TOURNAMENT_PRIZES     1296
#define IDC_MENU_ITEM13                 1297
#define IDC_BUYIN_HEADER                1297
#define IDC_STATIC_BANKROLL             1298
#define IDC_MENU_ITEM14                 1299
#define IDC_TOURN_TABLE_SCRIPT          1299
#define IDC_MENU_ITEM15                 1300
#define IDC_ENCRYPTION_LOCK             1300
#define IDC_REAL_TABLE_SCRIPT           1300
#define IDC_MENU_ITEM16                 1301
#define IDC_MENU_ITEM17                 1302
#define IDC_LOCK_ICON                   1302
#define IDC_MENU_ITEM18                 1303
#define IDC_MAX_TOURN_TABLES            1303
#define IDC_MENU_ITEM19                 1304
#define IDC_MAX_TOURN_TABLES_SPINNER    1304
#define IDC_MENU_ITEM20                 1305
#define IDC_STATIC_BUYIN_DETAILS        1305
#define IDC_MENU_ITEM21                 1306
#define IDC_STATIC_SERIALNO             1306
#define IDC_MENU_ITEM22                 1307
#define IDC_TIMEZONE_EXAMPLES           1307
#define IDC_MENU_ITEM23                 1308
#define IDC_ADDRESS_CHANGE_INFO         1308
#define IDC_MENU_ITEM24                 1309
#define IDC_CHKBOX_DISPLAY_SECONDS      1309
#define IDC_MENU_ITEM25                 1310
#define IDC_CHKBOX_DISPLAY_SHORT_UNITS  1310
#define IDC_MENU_ITEM26                 1311
#define IDC_CHKBOX_SAME_AS_PRE_EXPIRY   1311
#define IDC_MENU_ITEM27                 1312
#define IDC_CHKBOX_ALARM                1312
#define IDC_CHECK_DISABLE_ALL           1314
#define IDC_CHECK_ENABLE_ALL            1315
#define IDC_EDIT_CASHOUT                1315
#define IDC_TEXT_BLOCK                  1316
#define IDC_FOUND_PLAYER1               1317
#define IDC_EDIT_CASHOUT3               1317
#define IDC_FOUND_PLAYER2               1318
#define IDC_FOUND_PLAYER3               1319
#define IDC_FOUND_PLAYER4               1320
#define IDC_FOUND_PLAYER5               1321
#define IDC_TEXT_MATCHES                1325
#define IDC_BUTTON_SEARCH               1326
#define IDC_EDIT_SEARCH_EMAIL           1327
#define IDC_FILE_INFO                   1328
#define IDC_BUTTON_UPDATE_FILE          1329
#define IDC_BUTTON_PASTE                1330
#define IDC_MIN_HAND_RANK               1330
#define IDC_MIN_HAND_RANK_EDIT          1331
#define IDC_MIN_HAND_RANK_SPIN          1332
#define IDC_INFO_SELECT                 1333
#define IDC_INFO_COPY                   1334
#define IDC_ADMIN_INFO_EDIT             1335
#define IDC_TEXT_PLAYER_INFO            1336
#define IDC_REQINFO_DAYS                1337
#define IDC_TEXT_PLAYER_INFO2           1338
#define IDC_BUTTON_FIREPAY              1341
#define IDC_BUTTON_FIREPAYSETUP         1345
#define IDC_BUTTON_FIREPAY_INFO         1346
#define IDC_STATIC_FIREPAY              1349
#define IDC_EDIT_PHONE_NUMBER           1350
#define IDC_REQ_HH_APPLY                1352
#define IDC_CHECK_EMAIL_FROM            1353
#define IDC_CHECK_EMAIL_TO              1354
#define IDC_STORE_FROM_ID               1355
#define IDC_STORE_TO_ID                 1356
#define IDC_STATIC_PROCESSMARK_1        1356
#define IDC_STORE_AMOUNT                1357
#define IDC_STATIC_PROCESSMARK_2        1357
#define IDC_STATIC_PROCESSMARK_4        1359
#define IDC_STATIC_PROCESSMARK_5        1360
#define IDC_STATIC_PROCESSMARK_6        1361
#define IDC_STATIC_PROCESSSETENCE_1     1362
#define IDC_STATIC_PROCESSSETENCE_2     1363
#define IDC_STATIC_PROCESSSETENCE_3     1364
#define IDC_STATIC_PROCESSSETENCE_4     1365
#define IDC_STATIC_PROCESSSETENCE_5     1366
#define IDC_STATIC_PROCESSSETENCE_6     1367
#define IDC_STATIC_PROCESSMARK_3        1368
#define IDC_STATIC_MailingAddress       1370
#define IDSUBMIT                        1371
#define IDC_STATIC_SHOW_LARGE           1381
#define IDC_STATIC_1                    1382
#define IDC_STATIC_2                    1383
#define IDC_RAKED_GAMES                 1384
#define IDC_EPTS_STR                    1385
#define IDC_EPTS                        1386
#define IDC_EPTS_STR2                   1387
#define IDC_BUTTON_VISA                 1388
#define IDC_ABOUT_PAYPAL                1389
#define IDC_ABOUT_FIREPAY               1390
#define IDC_SIGN_FIREPAY                1391
#define IDC_MSGTEXT                     1394
#define IDC_SLASH                       1395
#define IDC_TEXT_1                      1396
#define IDC_TEXT_2                      1397
#define IDC_DOWNLOAD1                   1399
#define IDC_DOWNLOAD2                   1400
#define IDC_HIGH_HAND                   1401
#define IDC_NEWS_DETAILS                1402
#define IDC_STATIC_NEWS                 1403
#define IDC_RADIO_SRC_CCFEE             1409
#define IDC_RADIO_DEST_CCFEE            1413
#define IDC_LISTVIEWCTRL1               1414
#define IDC_MY_MONEY2                   1415
#define IDC_LINK                        1419
#define IDC_SIT_DOWN_20                 1420
#define IDC_LASTNAME                    1421
#define IDC_COMBO_DAY                   1422
#define IDC_COMBO_MONTH                 1423
#define IDC_COMBO_YEAR                  1424
#define IDC_PHONE                       1425
#define IDC_PAY_TO                      1426
#define IDC_COMMENTS                    1426
#define IDC_MONTH                       1427
#define IDC_HEART_ABOUT_US              1427
#define IDC_REFERED_BY                  1429
#define IDC_SECRET_QUESTION             1433
#define IDC_SECURE_PHRASE               1435
#define IDC_TAB                         1437
#define IDC_TOURN_TABLE1ON1_SCRIPT      1439
#define IDC_LIMIT                       1440
#define IDC_NEW_LIMIT                   1442
#define IDC_RAKE                        1444
#define IDC_PHONE2                      1445
#define IDM_SHOW_HOLDEM                 32771
#define IDM_SHOW_OMAHA                  32772
#define IDM_SHOW_7CS                    32773
#define ID_LOBBY_NOOPENTABLES           32774
#define ID_OPTIONS_PREFERENCES          32775
#define ID_OPTIONS_TELLAFRIENDABOUTPARADISEPOKER 32776
#define IDM_GOTO_TABLE1                 32777
#define IDM_GOTO_TABLE2                 32778
#define IDM_GOTO_TABLE3                 32779
#define IDM_GOTO_TABLE4                 32780
#define IDM_CHECK_FOR_UPDATE            32781
#define IDM_EDIT_USER_ACCOUNTS          32782
#define IDM_NETWORK_STATUS              32783
#define IDM_CHANGE_SHOTCLOCK            32784
#define IDM_CHANGE_PASSWORD             32785
#define IDM_OPTIONS_ALLINS              32786
#define IDM_OPTIONS_SHOW_CONNECT_MSG    32787
#define IDM_START_CHECK_RUN             32788
#define IDM_CHANGE_EMAIL                32789
#define IDM_REQUEST_ALLIN_RESET         32790
#define IDM_CHANGE_ALLINS               32791
#define IDM_ENABLE_SOUNDS               32792
#define IDM_ENABLE_ANIMATION            32793
#define IDM_ENABLE_4COLOR_DECK          32794
#define IDM_MOVE_TO_TOP_WAITLIST        32795
#define IDM_INSERT_BLANK_COMPUTER_NUM   32796
#define IDM_SHOW_7CS_HI_LO              32797
#define IDM_SHOW_OMAHA_HI_LO            32798
#define IDM_ENABLE_BAR_SNACKS           32799
#define IDM_OPTIMIZE_GRAPHICS           32800
#define IDM_CHANGE_ADDRESS              32802
#define IDC_PROMOTIONUPDATES            32807
#define IDM_TABLE_THEMES                32810
#define IDM_RETRIEVE_PASSW              32812
#define IDC_STATIC                      -1
#define IDC_STATIC_FRAME                65535
#define IDC_STATIC_FirstMessage         65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        293
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1446
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
